Bing Chen 

ST 554 Project Part 2 

3/19/2026

# Introduction 

In this project, we developed a PySpark-based data validation class named `SparkDataCheck`. Our class is designed to facilitate data validation and exploration. After defining the class and its associated methods, we will apply it to some real-world dataset here to perform various data quality checks, such as missing value detection, numerical range validation, and etc.

Now, let's import the class and start a spark session.

In [10]:
from SparkDataCheck import SparkDataCheck
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
import pandas as pd


spark = SparkSession.builder \
    .appName("SparkDataCheck") \
    .getOrCreate()

# From csv 

Next, let's create an instance of the class from a `.csv` file.

In [11]:
air = SparkDataCheck.from_csv(
    spark,
    "air.csv"
)

air.df.show()

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|  0|3/10/2004|2026-03-20 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|  1|3/10/2004|2026-03-20 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|  2|3/10/2004|2026-03-20 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|  3|3/10/2004|2026-03-20 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|  4|3/10/2004|2026-03-20 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
|  5|3/10/2004|2026-03-20 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|
|  6|3/11/2004|2026-03-20 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|
|  7|3/11/2004|2026-03-20 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|
|  8|3/11/2004|2026-03-20 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|
|  9|3/11/2004|2026-03-20 03:00:00|   0.6|       1010|      19|     1.7|          561|   -200|        1705|   -200|        1235|        501|10.3|60.2|0.7517|
| 10|3/11/2004|2026-03-20 04:00:00|-200.0|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|
| 11|3/11/2004|2026-03-20 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|
| 12|3/11/2004|2026-03-20 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|
| 13|3/11/2004|2026-03-20 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|
| 14|3/11/2004|2026-03-20 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|
| 15|3/11/2004|2026-03-20 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|
| 16|3/11/2004|2026-03-20 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|
| 17|3/11/2004|2026-03-20 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|
| 18|3/11/2004|2026-03-20 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|
| 19|3/11/2004|2026-03-20 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 20 rows

26/03/20 16:37:49 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-bchen29@ncsu.edu/ST-554-Project2/Part2/air.csv

Using this air quality data, let's see some examples of how to use methods in this class. Recall that in this dataset, missing values are tagged with -200 value, so let's replace them with `None` first.

In [12]:
air.df = air.df.na.replace(-200, None)

## Check if a numeric variable is within a specified range.

Next, we might want to check if `PT08.S1(CO)` values specifically are all above 0.

In [13]:
air.within_range("PT08.S1(CO)", lower=0, upper = None).df.show()

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|PT08.S1(CO)_in_range|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+
|  0|3/10/2004|2026-03-20 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|                true|
|  1|3/10/2004|2026-03-20 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|                true|
|  2|3/10/2004|2026-03-20 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|                true|
|  3|3/10/2004|2026-03-20 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|                true|
|  4|3/10/2004|2026-03-20 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|                true|
|  5|3/10/2004|2026-03-20 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|                true|
|  6|3/11/2004|2026-03-20 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|                true|
|  7|3/11/2004|2026-03-20 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|                true|
|  8|3/11/2004|2026-03-20 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|                true|
|  9|3/11/2004|2026-03-20 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517|                true|
| 10|3/11/2004|2026-03-20 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|                true|
| 11|3/11/2004|2026-03-20 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|                true|
| 12|3/11/2004|2026-03-20 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|                true|
| 13|3/11/2004|2026-03-20 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|                true|
| 14|3/11/2004|2026-03-20 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|                true|
| 15|3/11/2004|2026-03-20 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|                true|
| 16|3/11/2004|2026-03-20 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|                true|
| 17|3/11/2004|2026-03-20 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|                true|
| 18|3/11/2004|2026-03-20 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|                true|
| 19|3/11/2004|2026-03-20 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|                true|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+
only showing top 20 rows

26/03/20 16:37:50 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-bchen29@ncsu.edu/ST-554-Project2/Part2/air.csv

Let's see if the values are all below 2000.

In [14]:
air.within_range("PT08.S1(CO)", lower=None, upper = 1300).df.show()

26/03/20 16:37:50 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-bchen29@ncsu.edu/ST-554-Project2/Part2/air.csv

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|PT08.S1(CO)_in_range|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+
|  0|3/10/2004|2026-03-20 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|               false|
|  1|3/10/2004|2026-03-20 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|                true|
|  2|3/10/2004|2026-03-20 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|               false|
|  3|3/10/2004|2026-03-20 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|               false|
|  4|3/10/2004|2026-03-20 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|                true|
|  5|3/10/2004|2026-03-20 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|                true|
|  6|3/11/2004|2026-03-20 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|                true|
|  7|3/11/2004|2026-03-20 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|                true|
|  8|3/11/2004|2026-03-20 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|                true|
|  9|3/11/2004|2026-03-20 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517|                true|
| 10|3/11/2004|2026-03-20 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|                true|
| 11|3/11/2004|2026-03-20 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|                true|
| 12|3/11/2004|2026-03-20 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|                true|
| 13|3/11/2004|2026-03-20 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|                true|
| 14|3/11/2004|2026-03-20 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|               false|
| 15|3/11/2004|2026-03-20 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|               false|
| 16|3/11/2004|2026-03-20 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|                true|
| 17|3/11/2004|2026-03-20 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|                true|
| 18|3/11/2004|2026-03-20 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|                true|
| 19|3/11/2004|2026-03-20 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|                true|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+
only showing top 20 rows

How about between 0 to 1500?

In [15]:
air.within_range("PT08.S1(CO)", lower=0, upper = 10).df.show()

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|PT08.S1(CO)_in_range|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+
|  0|3/10/2004|2026-03-20 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|               false|
|  1|3/10/2004|2026-03-20 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|               false|
|  2|3/10/2004|2026-03-20 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|               false|
|  3|3/10/2004|2026-03-20 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|               false|
|  4|3/10/2004|2026-03-20 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|               false|
|  5|3/10/2004|2026-03-20 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|               false|
|  6|3/11/2004|2026-03-20 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|               false|
|  7|3/11/2004|2026-03-20 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|               false|
|  8|3/11/2004|2026-03-20 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|               false|
|  9|3/11/2004|2026-03-20 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517|               false|
| 10|3/11/2004|2026-03-20 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|               false|
| 11|3/11/2004|2026-03-20 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|               false|
| 12|3/11/2004|2026-03-20 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|               false|
| 13|3/11/2004|2026-03-20 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|               false|
| 14|3/11/2004|2026-03-20 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|               false|
| 15|3/11/2004|2026-03-20 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|               false|
| 16|3/11/2004|2026-03-20 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|               false|
| 17|3/11/2004|2026-03-20 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|               false|
| 18|3/11/2004|2026-03-20 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|               false|
| 19|3/11/2004|2026-03-20 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|               false|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+
only showing top 20 rows

26/03/20 16:37:50 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-bchen29@ncsu.edu/ST-554-Project2/Part2/air.csv

What if we accidentally passed through a string variable?

In [16]:
air.within_range("Date", lower=0, upper = None).df.show()

Column 'Date' is not numeric.
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|PT08.S1(CO)_in_range|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+
|  0|3/10/2004|2026-03-20 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|               false|
|  1|3/10/2004|2026-03-20 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|               false|
|  2|3/10/2004|2026-03-20 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|               false|
|  3|3/10/2004|2026-03-20 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|               false|
|  4|3/10/2004|2026-03-20 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|               false|
|  5|3/10/2004|2026-03-20 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|               false|
|  6|3/11/2004|2026-03-20 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|               false|
|  7|3/11/2004|2026-03-20 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|               false|
|  8|3/11/2004|2026-03-20 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|               false|
|  9|3/11/2004|2026-03-20 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517|               false|
| 10|3/11/2004|2026-03-20 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|               false|
| 11|3/11/2004|2026-03-20 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|               false|
| 12|3/11/2004|2026-03-20 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|               false|
| 13|3/11/2004|2026-03-20 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|               false|
| 14|3/11/2004|2026-03-20 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|               false|
| 15|3/11/2004|2026-03-20 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|               false|
| 16|3/11/2004|2026-03-20 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|               false|
| 17|3/11/2004|2026-03-20 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|               false|
| 18|3/11/2004|2026-03-20 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|               false|
| 19|3/11/2004|2026-03-20 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|               false|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+
only showing top 20 rows

26/03/20 16:37:50 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-bchen29@ncsu.edu/ST-554-Project2/Part2/air.csv

Nice! It prints out message noting that `Date` is not a numeric column and returns the original data frame.

What if we forgot to pass on any bounds?

In [17]:
air.within_range("PT08.S1(CO)").df.show()

At least one of 'lower' or 'upper' must be provided.
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|PT08.S1(CO)_in_range|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+
|  0|3/10/2004|2026-03-20 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|               false|
|  1|3/10/2004|2026-03-20 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|               false|
|  2|3/10/2004|2026-03-20 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|               false|
|  3|3/10/2004|2026-03-20 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|               false|
|  4|3/10/2004|2026-03-20 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|               false|
|  5|3/10/2004|2026-03-20 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|               false|
|  6|3/11/2004|2026-03-20 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|               false|
|  7|3/11/2004|2026-03-20 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|               false|
|  8|3/11/2004|2026-03-20 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|               false|
|  9|3/11/2004|2026-03-20 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517|               false|
| 10|3/11/2004|2026-03-20 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|               false|
| 11|3/11/2004|2026-03-20 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|               false|
| 12|3/11/2004|2026-03-20 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|               false|
| 13|3/11/2004|2026-03-20 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|               false|
| 14|3/11/2004|2026-03-20 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|               false|
| 15|3/11/2004|2026-03-20 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|               false|
| 16|3/11/2004|2026-03-20 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|               false|
| 17|3/11/2004|2026-03-20 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|               false|
| 18|3/11/2004|2026-03-20 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|               false|
| 19|3/11/2004|2026-03-20 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|               false|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+
only showing top 20 rows

26/03/20 16:37:51 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-bchen29@ncsu.edu/ST-554-Project2/Part2/air.csv

So, it prints out that at least one bound need to be supplied. Great!

## Check if a categorical variable is within specified levels. 

Say we want to classify `PT08.S1(CO)` into 3 levels to allow users to quickly understand if air quality is "Safe" or "Hazardous" without knowing technical sensor specs. Consider the 3 ranks below: 

 - Low: Readings below 970
 - Mid: Readings between 970 and 1,180
 - High: Readings above 1,180
 
 So, let's create a new variable for the transformed `PT08.S1(CO)`.

In [18]:
air.df = air.df.withColumn(
    "PT08_S1(CO)_cat",
    F.when(F.col("`PT08.S1(CO)`") < 970, "Low")
     .when((F.col("`PT08.S1(CO)`") >= 970) & (F.col("`PT08.S1(CO)`") <= 1180), "Mid")
     .when(F.col("`PT08.S1(CO)`") > 1180, "High")
     .otherwise(None)
)

Let's quickly check the results.

In [19]:
air.df.select("`PT08.S1(CO)`","PT08_S1(CO)_cat").show(10)

+-----------+---------------+
|PT08.S1(CO)|PT08_S1(CO)_cat|
+-----------+---------------+
|       1360|           High|
|       1292|           High|
|       1402|           High|
|       1376|           High|
|       1272|           High|
|       1197|           High|
|       1185|           High|
|       1136|            Mid|
|       1094|            Mid|
|       1010|            Mid|
+-----------+---------------+
only showing top 10 rows

Looks like it's working correctly. Let's try out our method to see if all values are within the levels.

In [20]:
air.within_levels("PT08.S1(CO)", levels = ["Low", "Mid", "High"]).df.show()

Column 'PT08.S1(CO)' is not a string column.
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|PT08.S1(CO)_in_range|PT08_S1(CO)_cat|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+
|  0|3/10/2004|2026-03-20 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|               false|           High|
|  1|3/10/2004|2026-03-20 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|               false|           High|
|  2|3/10/2004|2026-03-20 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|               false|           High|
|  3|3/10/2004|2026-03-20 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|               false|           High|
|  4|3/10/2004|2026-03-20 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|               false|           High|
|  5|3/10/2004|2026-03-20 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|               false|           High|
|  6|3/11/2004|2026-03-20 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|               false|           High|
|  7|3/11/2004|2026-03-20 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|               false|            Mid|
|  8|3/11/2004|2026-03-20 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|               false|            Mid|
|  9|3/11/2004|2026-03-20 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517|               false|            Mid|
| 10|3/11/2004|2026-03-20 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|               false|            Mid|
| 11|3/11/2004|2026-03-20 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|               false|            Mid|
| 12|3/11/2004|2026-03-20 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|               false|            Mid|
| 13|3/11/2004|2026-03-20 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|               false|            Mid|
| 14|3/11/2004|2026-03-20 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|               false|           High|
| 15|3/11/2004|2026-03-20 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|               false|           High|
| 16|3/11/2004|2026-03-20 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|               false|           High|
| 17|3/11/2004|2026-03-20 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|               false|            Mid|
| 18|3/11/2004|2026-03-20 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|               false|           High|
| 19|3/11/2004|2026-03-20 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|               false|           High|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+
only showing top 20 rows

26/03/20 16:37:52 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-bchen29@ncsu.edu/ST-554-Project2/Part2/air.csv

Oops! Accidentally passed through the numeric column of `PT08.S1(CO)` instead of the categorical column we just created! So, let's do that again.

In [21]:
air.within_levels("PT08_S1(CO)_cat", levels = ["Low", "Mid", "High"]).df.show()

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|PT08.S1(CO)_in_range|PT08_S1(CO)_cat|PT08_S1(CO)_cat_in_levels|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+
|  0|3/10/2004|2026-03-20 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|               false|           High|                     true|
|  1|3/10/2004|2026-03-20 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|               false|           High|                     true|
|  2|3/10/2004|2026-03-20 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|               false|           High|                     true|
|  3|3/10/2004|2026-03-20 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|               false|           High|                     true|
|  4|3/10/2004|2026-03-20 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|               false|           High|                     true|
|  5|3/10/2004|2026-03-20 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|               false|           High|                     true|
|  6|3/11/2004|2026-03-20 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|               false|           High|                     true|
|  7|3/11/2004|2026-03-20 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|               false|            Mid|                     true|
|  8|3/11/2004|2026-03-20 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|               false|            Mid|                     true|
|  9|3/11/2004|2026-03-20 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517|               false|            Mid|                     true|
| 10|3/11/2004|2026-03-20 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|               false|            Mid|                     true|
| 11|3/11/2004|2026-03-20 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|               false|            Mid|                     true|
| 12|3/11/2004|2026-03-20 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|               false|            Mid|                     true|
| 13|3/11/2004|2026-03-20 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|               false|            Mid|                     true|
| 14|3/11/2004|2026-03-20 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|               false|           High|                     true|
| 15|3/11/2004|2026-03-20 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|               false|           High|                     true|
| 16|3/11/2004|2026-03-20 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|               false|           High|                     true|
| 17|3/11/2004|2026-03-20 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|               false|            Mid|                     true|
| 18|3/11/2004|2026-03-20 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|               false|           High|                     true|
| 19|3/11/2004|2026-03-20 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|               false|           High|                     true|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+
only showing top 20 rows

26/03/20 16:37:52 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-bchen29@ncsu.edu/ST-554-Project2/Part2/air.csv

Looks good! Let's try another variable.  We can `Absolute Humidity` into 

- Dry: AH < 0.8  
- Optimal: 0.8 ≤ AH ≤ 1.5  
- Humid: AH > 1.5

In [22]:
air.df = air.df.withColumn(
    "abs_humidity_cat",
    F.when(F.col("AH") < 0.8, "Dry")
     .when((F.col("AH") >= 0.8) & (F.col("AH") <= 1.5), "Optimal")
     .when(F.col("AH") > 1.5, "Humid")
     .otherwise(None)
)

In [23]:
air.within_levels("abs_humidity_cat", levels = ["Optimal", "Humid"]).df.show()

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+----------------+--------------------------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|PT08.S1(CO)_in_range|PT08_S1(CO)_cat|PT08_S1(CO)_cat_in_levels|abs_humidity_cat|abs_humidity_cat_in_levels|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+----------------+--------------------------+
|  0|3/10/2004|2026-03-20 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|               false|           High|                     true|             Dry|                     false|
|  1|3/10/2004|2026-03-20 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|               false|           High|                     true|             Dry|                     false|
|  2|3/10/2004|2026-03-20 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|               false|           High|                     true|             Dry|                     false|
|  3|3/10/2004|2026-03-20 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|               false|           High|                     true|             Dry|                     false|
|  4|3/10/2004|2026-03-20 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|               false|           High|                     true|             Dry|                     false|
|  5|3/10/2004|2026-03-20 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|               false|           High|                     true|             Dry|                     false|
|  6|3/11/2004|2026-03-20 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|               false|           High|                     true|             Dry|                     false|
|  7|3/11/2004|2026-03-20 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|               false|            Mid|                     true|             Dry|                     false|
|  8|3/11/2004|2026-03-20 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|               false|            Mid|                     true|             Dry|                     false|
|  9|3/11/2004|2026-03-20 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517|               false|            Mid|                     true|             Dry|                     false|
| 10|3/11/2004|2026-03-20 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|               false|            Mid|                     true|             Dry|                     false|
| 11|3/11/2004|2026-03-20 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|               false|            Mid|                     true|             Dry|                     false|
| 12|3/11/2004|2026-03-20 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|               false|            Mid|                     true|             Dry|                     false|
| 13|3/11/2004|2026-03-20 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|               false|            Mid|                     true|             Dry|                     false|
| 14|3/11/2004|2026-03-20 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|               false|           High|                     true|             Dry|                     false|
| 15|3/11/2004|2026-03-20 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|               false|           High|                     true|             Dry|                     false|
| 16|3/11/2004|2026-03-20 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|               false|           High|                     true|             Dry|                     false|
| 17|3/11/2004|2026-03-20 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|               false|            Mid|                     true|             Dry|                     false|
| 18|3/11/2004|2026-03-20 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|               false|           High|                     true|             Dry|                     false|
| 19|3/11/2004|2026-03-20 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|               false|           High|                     true|         Optimal|                      true|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+----------------+--------------------------+
only showing top 20 rows

26/03/20 16:37:53 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-bchen29@ncsu.edu/ST-554-Project2/Part2/air.csv

Why is there so many `false`? Oops! Accidentally missed out a level!

In [24]:
air.within_levels("abs_humidity_cat", levels = ["Dry", "Optimal", "Humid"]).df.show()

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+----------------+--------------------------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|PT08.S1(CO)_in_range|PT08_S1(CO)_cat|PT08_S1(CO)_cat_in_levels|abs_humidity_cat|abs_humidity_cat_in_levels|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+----------------+--------------------------+
|  0|3/10/2004|2026-03-20 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|               false|           High|                     true|             Dry|                      true|
|  1|3/10/2004|2026-03-20 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|               false|           High|                     true|             Dry|                      true|
|  2|3/10/2004|2026-03-20 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|               false|           High|                     true|             Dry|                      true|
|  3|3/10/2004|2026-03-20 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|               false|           High|                     true|             Dry|                      true|
|  4|3/10/2004|2026-03-20 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|               false|           High|                     true|             Dry|                      true|
|  5|3/10/2004|2026-03-20 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|               false|           High|                     true|             Dry|                      true|
|  6|3/11/2004|2026-03-20 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|               false|           High|                     true|             Dry|                      true|
|  7|3/11/2004|2026-03-20 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|               false|            Mid|                     true|             Dry|                      true|
|  8|3/11/2004|2026-03-20 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|               false|            Mid|                     true|             Dry|                      true|
|  9|3/11/2004|2026-03-20 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517|               false|            Mid|                     true|             Dry|                      true|
| 10|3/11/2004|2026-03-20 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|               false|            Mid|                     true|             Dry|                      true|
| 11|3/11/2004|2026-03-20 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|               false|            Mid|                     true|             Dry|                      true|
| 12|3/11/2004|2026-03-20 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|               false|            Mid|                     true|             Dry|                      true|
| 13|3/11/2004|2026-03-20 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|               false|            Mid|                     true|             Dry|                      true|
| 14|3/11/2004|2026-03-20 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|               false|           High|                     true|             Dry|                      true|
| 15|3/11/2004|2026-03-20 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|               false|           High|                     true|             Dry|                      true|
| 16|3/11/2004|2026-03-20 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|               false|           High|                     true|             Dry|                      true|
| 17|3/11/2004|2026-03-20 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|               false|            Mid|                     true|             Dry|                      true|
| 18|3/11/2004|2026-03-20 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|               false|           High|                     true|             Dry|                      true|
| 19|3/11/2004|2026-03-20 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|               false|           High|                     true|         Optimal|                      true|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+----------------+--------------------------+
only showing top 20 rows

26/03/20 16:37:53 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-bchen29@ncsu.edu/ST-554-Project2/Part2/air.csv

Now it's looking good.

## Check Missingness 

When we first look at a dataset, we always want to know how complete is the data, are there any missing values, how are they coded? From the data description, we know that missing values are coded -200 and we already replaced that with `None`. So now, let's check where a value is missing for some variables.

In [25]:
air.is_missing("`PT08.S1(CO)`").df.show()

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+----------------+--------------------------+------------------------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|PT08.S1(CO)_in_range|PT08_S1(CO)_cat|PT08_S1(CO)_cat_in_levels|abs_humidity_cat|abs_humidity_cat_in_levels|`PT08.S1(CO)`_is_missing|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+----------------+--------------------------+------------------------+
|  0|3/10/2004|2026-03-20 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|               false|           High|                     true|             Dry|                      true|                   false|
|  1|3/10/2004|2026-03-20 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|               false|           High|                     true|             Dry|                      true|                   false|
|  2|3/10/2004|2026-03-20 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|               false|           High|                     true|             Dry|                      true|                   false|
|  3|3/10/2004|2026-03-20 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|               false|           High|                     true|             Dry|                      true|                   false|
|  4|3/10/2004|2026-03-20 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|               false|           High|                     true|             Dry|                      true|                   false|
|  5|3/10/2004|2026-03-20 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|               false|           High|                     true|             Dry|                      true|                   false|
|  6|3/11/2004|2026-03-20 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|               false|           High|                     true|             Dry|                      true|                   false|
|  7|3/11/2004|2026-03-20 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|               false|            Mid|                     true|             Dry|                      true|                   false|
|  8|3/11/2004|2026-03-20 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|               false|            Mid|                     true|             Dry|                      true|                   false|
|  9|3/11/2004|2026-03-20 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517|               false|            Mid|                     true|             Dry|                      true|                   false|
| 10|3/11/2004|2026-03-20 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|               false|            Mid|                     true|             Dry|                      true|                   false|
| 11|3/11/2004|2026-03-20 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|               false|            Mid|                     true|             Dry|                      true|                   false|
| 12|3/11/2004|2026-03-20 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|               false|            Mid|                     true|             Dry|                      true|                   false|
| 13|3/11/2004|2026-03-20 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|               false|            Mid|                     true|             Dry|                      true|                   false|
| 14|3/11/2004|2026-03-20 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|               false|           High|                     true|             Dry|                      true|                   false|
| 15|3/11/2004|2026-03-20 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|               false|           High|                     true|             Dry|                      true|                   false|
| 16|3/11/2004|2026-03-20 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|               false|           High|                     true|             Dry|                      true|                   false|
| 17|3/11/2004|2026-03-20 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|               false|            Mid|                     true|             Dry|                      true|                   false|
| 18|3/11/2004|2026-03-20 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|               false|           High|                     true|             Dry|                      true|                   false|
| 19|3/11/2004|2026-03-20 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|               false|           High|                     true|         Optimal|                      true|                   false|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+----------------+--------------------------+------------------------+
only showing top 20 rows

26/03/20 16:37:54 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-bchen29@ncsu.edu/ST-554-Project2/Part2/air.csv

In [26]:
air.is_missing("AH").df.show()

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+----------------+--------------------------+------------------------+-------------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|PT08.S1(CO)_in_range|PT08_S1(CO)_cat|PT08_S1(CO)_cat_in_levels|abs_humidity_cat|abs_humidity_cat_in_levels|`PT08.S1(CO)`_is_missing|AH_is_missing|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+----------------+--------------------------+------------------------+-------------+
|  0|3/10/2004|2026-03-20 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|               false|           High|                     true|             Dry|                      true|                   false|        false|
|  1|3/10/2004|2026-03-20 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|               false|           High|                     true|             Dry|                      true|                   false|        false|
|  2|3/10/2004|2026-03-20 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|               false|           High|                     true|             Dry|                      true|                   false|        false|
|  3|3/10/2004|2026-03-20 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|               false|           High|                     true|             Dry|                      true|                   false|        false|
|  4|3/10/2004|2026-03-20 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|               false|           High|                     true|             Dry|                      true|                   false|        false|
|  5|3/10/2004|2026-03-20 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|               false|           High|                     true|             Dry|                      true|                   false|        false|
|  6|3/11/2004|2026-03-20 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|               false|           High|                     true|             Dry|                      true|                   false|        false|
|  7|3/11/2004|2026-03-20 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|               false|            Mid|                     true|             Dry|                      true|                   false|        false|
|  8|3/11/2004|2026-03-20 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|               false|            Mid|                     true|             Dry|                      true|                   false|        false|
|  9|3/11/2004|2026-03-20 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517|               false|            Mid|                     true|             Dry|                      true|                   false|        false|
| 10|3/11/2004|2026-03-20 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|               false|            Mid|                     true|             Dry|                      true|                   false|        false|
| 11|3/11/2004|2026-03-20 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|               false|            Mid|                     true|             Dry|                      true|                   false|        false|
| 12|3/11/2004|2026-03-20 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|               false|            Mid|                     true|             Dry|                      true|                   false|        false|
| 13|3/11/2004|2026-03-20 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|               false|            Mid|                     true|             Dry|                      true|                   false|        false|
| 14|3/11/2004|2026-03-20 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|               false|           High|                     true|             Dry|                      true|                   false|        false|
| 15|3/11/2004|2026-03-20 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|               false|           High|                     true|             Dry|                      true|                   false|        false|
| 16|3/11/2004|2026-03-20 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|               false|           High|                     true|             Dry|                      true|                   false|        false|
| 17|3/11/2004|2026-03-20 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|               false|            Mid|                     true|             Dry|                      true|                   false|        false|
| 18|3/11/2004|2026-03-20 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|               false|           High|                     true|             Dry|                      true|                   false|        false|
| 19|3/11/2004|2026-03-20 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|               false|           High|                     true|         Optimal|                      true|                   false|        false|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+----------------+--------------------------+------------------------+-------------+
only showing top 20 rows

26/03/20 16:37:54 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-bchen29@ncsu.edu/ST-554-Project2/Part2/air.csv

In [27]:
air.is_missing("NMHC(GT)").df.show()

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+----------------+--------------------------+------------------------+-------------+-------------------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|PT08.S1(CO)_in_range|PT08_S1(CO)_cat|PT08_S1(CO)_cat_in_levels|abs_humidity_cat|abs_humidity_cat_in_levels|`PT08.S1(CO)`_is_missing|AH_is_missing|NMHC(GT)_is_missing|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+----------------+--------------------------+------------------------+-------------+-------------------+
|  0|3/10/2004|2026-03-20 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|
|  1|3/10/2004|2026-03-20 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|
|  2|3/10/2004|2026-03-20 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|
|  3|3/10/2004|2026-03-20 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|
|  4|3/10/2004|2026-03-20 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|
|  5|3/10/2004|2026-03-20 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|
|  6|3/11/2004|2026-03-20 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|
|  7|3/11/2004|2026-03-20 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|               false|            Mid|                     true|             Dry|                      true|                   false|        false|              false|
|  8|3/11/2004|2026-03-20 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|               false|            Mid|                     true|             Dry|                      true|                   false|        false|              false|
|  9|3/11/2004|2026-03-20 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517|               false|            Mid|                     true|             Dry|                      true|                   false|        false|              false|
| 10|3/11/2004|2026-03-20 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|               false|            Mid|                     true|             Dry|                      true|                   false|        false|              false|
| 11|3/11/2004|2026-03-20 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|               false|            Mid|                     true|             Dry|                      true|                   false|        false|              false|
| 12|3/11/2004|2026-03-20 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|               false|            Mid|                     true|             Dry|                      true|                   false|        false|              false|
| 13|3/11/2004|2026-03-20 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|               false|            Mid|                     true|             Dry|                      true|                   false|        false|              false|
| 14|3/11/2004|2026-03-20 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|
| 15|3/11/2004|2026-03-20 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|
| 16|3/11/2004|2026-03-20 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|
| 17|3/11/2004|2026-03-20 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|               false|            Mid|                     true|             Dry|                      true|                   false|        false|              false|
| 18|3/11/2004|2026-03-20 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|
| 19|3/11/2004|2026-03-20 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|               false|           High|                     true|         Optimal|                      true|                   false|        false|              false|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+----------------+--------------------------+------------------------+-------------+-------------------+
only showing top 20 rows

26/03/20 16:37:54 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-bchen29@ncsu.edu/ST-554-Project2/Part2/air.csv

In [28]:
air.is_missing("Date").df.show()

26/03/20 16:37:54 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-bchen29@ncsu.edu/ST-554-Project2/Part2/air.csv

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+----------------+--------------------------+------------------------+-------------+-------------------+---------------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|PT08.S1(CO)_in_range|PT08_S1(CO)_cat|PT08_S1(CO)_cat_in_levels|abs_humidity_cat|abs_humidity_cat_in_levels|`PT08.S1(CO)`_is_missing|AH_is_missing|NMHC(GT)_is_missing|Date_is_missing|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+----------------+--------------------------+------------------------+-------------+-------------------+---------------+
|  0|3/10/2004|2026-03-20 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|          false|
|  1|3/10/2004|2026-03-20 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|          false|
|  2|3/10/2004|2026-03-20 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|          false|
|  3|3/10/2004|2026-03-20 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|          false|
|  4|3/10/2004|2026-03-20 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|          false|
|  5|3/10/2004|2026-03-20 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|          false|
|  6|3/11/2004|2026-03-20 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|          false|
|  7|3/11/2004|2026-03-20 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|               false|            Mid|                     true|             Dry|                      true|                   false|        false|              false|          false|
|  8|3/11/2004|2026-03-20 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|               false|            Mid|                     true|             Dry|                      true|                   false|        false|              false|          false|
|  9|3/11/2004|2026-03-20 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517|               false|            Mid|                     true|             Dry|                      true|                   false|        false|              false|          false|
| 10|3/11/2004|2026-03-20 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|               false|            Mid|                     true|             Dry|                      true|                   false|        false|              false|          false|
| 11|3/11/2004|2026-03-20 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|               false|            Mid|                     true|             Dry|                      true|                   false|        false|              false|          false|
| 12|3/11/2004|2026-03-20 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|               false|            Mid|                     true|             Dry|                      true|                   false|        false|              false|          false|
| 13|3/11/2004|2026-03-20 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|               false|            Mid|                     true|             Dry|                      true|                   false|        false|              false|          false|
| 14|3/11/2004|2026-03-20 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|          false|
| 15|3/11/2004|2026-03-20 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|          false|
| 16|3/11/2004|2026-03-20 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|          false|
| 17|3/11/2004|2026-03-20 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|               false|            Mid|                     true|             Dry|                      true|                   false|        false|              false|          false|
| 18|3/11/2004|2026-03-20 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|               false|           High|                     true|             Dry|                      true|                   false|        false|              false|          false|
| 19|3/11/2004|2026-03-20 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|               false|           High|                     true|         Optimal|                      true|                   false|        false|              false|          false|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+--------------------+---------------+-------------------------+----------------+--------------------------+------------------------+-------------+-------------------+---------------+
only showing top 20 rows

Looks good!

## Report the min and max of a given numeric column 

We previously checked if `PT08.S1(CO)` is within a specific range of interest. But what if we have no idea where the values should fall? This method is helpful to tell us this information.

In [29]:
air.min_max("PT08.S1(CO)").show()

+---------------+---------------+
|PT08.S1(CO)_min|PT08.S1(CO)_max|
+---------------+---------------+
|            647|           2040|
+---------------+---------------+

In [30]:
air.min_max("PT08_S1(CO)_cat")

Column 'PT08_S1(CO)_cat' is not numeric. Please give a numeric column.

We can't use this method on string variables! 

I want to see the min and max of `PT08.S1(CO)` for each levels `Absolute Humidity`.

In [31]:
air.min_max("PT08.S1(CO)", "abs_humidity_cat").show()

+----------------+---------------+---------------+
|abs_humidity_cat|PT08.S1(CO)_min|PT08.S1(CO)_max|
+----------------+---------------+---------------+
|            NULL|           NULL|           NULL|
|           Humid|            760|           1915|
|             Dry|            647|           1973|
|         Optimal|            704|           2040|
+----------------+---------------+---------------+

We can simply see that min and max for all numeric variables!

In [32]:
air.min_max().show()

26/03/20 16:37:56 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.
26/03/20 16:37:56 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-bchen29@ncsu.edu/ST-554-Project2/Part2/air.csv

+-------+-------+----------+----------+---------------+---------------+------------+------------+------------+------------+-----------------+-----------------+-----------+-----------+----------------+----------------+-----------+-----------+----------------+----------------+---------------+---------------+-----+-----+------+------+------+------+
|_c0_min|_c0_max|CO(GT)_min|CO(GT)_max|PT08.S1(CO)_min|PT08.S1(CO)_max|NMHC(GT)_min|NMHC(GT)_max|C6H6(GT)_min|C6H6(GT)_max|PT08.S2(NMHC)_min|PT08.S2(NMHC)_max|NOx(GT)_min|NOx(GT)_max|PT08.S3(NOx)_min|PT08.S3(NOx)_max|NO2(GT)_min|NO2(GT)_max|PT08.S4(NO2)_min|PT08.S4(NO2)_max|PT08.S5(O3)_min|PT08.S5(O3)_max|T_min|T_max|RH_min|RH_max|AH_min|AH_max|
+-------+-------+----------+----------+---------------+---------------+------------+------------+------------+------------+-----------------+-----------------+-----------+-----------+----------------+----------------+-----------+-----------+----------------+----------------+---------------+---------------+-----+-----+------+------+------+------+
|      0|   9356|       0.1|      11.9|            647|           2040|           7|        1189|         0.1|        63.7|              383|             2214|          2|       1479|             322|            2683|          2|        340|             551|            2775|            221|           2523| -1.9| 44.6|   9.2|  88.7|0.1847| 2.231|
+-------+-------+----------+----------+---------------+---------------+------------+------------+------------+------------+-----------------+-----------------+-----------+-----------+----------------+----------------+-----------+-----------+----------------+----------------+---------------+---------------+-----+-----+------+------+------+------+

In [33]:
air.min_max(col_name = None, group_by = "abs_humidity_cat").show()

26/03/20 16:37:57 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , AH
 Schema: _c0, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-bchen29@ncsu.edu/ST-554-Project2/Part2/air.csv

+----------------+-------+-------+----------+----------+---------------+---------------+------------+------------+------------+------------+-----------------+-----------------+-----------+-----------+----------------+----------------+-----------+-----------+----------------+----------------+---------------+---------------+-----+-----+------+------+------+------+
|abs_humidity_cat|_c0_min|_c0_max|CO(GT)_min|CO(GT)_max|PT08.S1(CO)_min|PT08.S1(CO)_max|NMHC(GT)_min|NMHC(GT)_max|C6H6(GT)_min|C6H6(GT)_max|PT08.S2(NMHC)_min|PT08.S2(NMHC)_max|NOx(GT)_min|NOx(GT)_max|PT08.S3(NOx)_min|PT08.S3(NOx)_max|NO2(GT)_min|NO2(GT)_max|PT08.S4(NO2)_min|PT08.S4(NO2)_max|PT08.S5(O3)_min|PT08.S5(O3)_max|T_min|T_max|RH_min|RH_max|AH_min|AH_max|
+----------------+-------+-------+----------+----------+---------------+---------------+------------+------------+------------+------------+-----------------+-----------------+-----------+-----------+----------------+----------------+-----------+-----------+----------------+----------------+---------------+---------------+-----+-----+------+------+------+------+
|           Humid|   1971|   5760|       0.1|       9.5|            760|           1915|        NULL|        NULL|         1.0|        52.1|              494|             2007|          2|       1052|             325|            1527|          5|        226|            1276|            2775|            396|           2519| 16.5| 40.5|  21.7|  87.2|1.5002| 2.231|
|             Dry|      0|   9356|       0.1|       9.1|            647|           1973|           7|         974|         0.1|        63.7|              383|             2214|         10|       1345|             346|            2683|          9|        333|             551|            2414|            221|           2522| -1.9| 38.3|   9.2|  86.6|0.1847|0.7999|
|         Optimal|     19|   9343|       0.1|      11.9|            704|           2040|          11|        1189|         0.5|        50.8|              437|             1983|          4|       1479|             322|            2095|          2|        288|             961|            2746|            320|           2523|  6.2| 44.6|   9.6|  88.7|0.8002|1.4999|
+----------------+-------+-------+----------+----------+---------------+---------------+------------+------------+------------+------------+-----------------+-----------------+-----------+-----------+----------------+----------------+-----------+-----------+----------------+----------------+---------------+---------------+-----+-----+------+------+------+------+

## Count the number of each levels for a given string variable

We may be interested in how many observations fall under each `PT08.S1(CO)` category we created.

In [34]:
air.count_level("PT08_S1(CO)_cat").show()

+---------------+-----+
|PT08_S1(CO)_cat|count|
+---------------+-----+
|           NULL|  366|
|           High| 2789|
|            Low| 2819|
|            Mid| 3383|
+---------------+-----+

Most of our data falls in to the Mid category! 

Let's try passing 2 variables.

In [35]:
air.count_level("PT08_S1(CO)_cat", "abs_humidity_cat").show()

+---------------+----------------+-----+
|PT08_S1(CO)_cat|abs_humidity_cat|count|
+---------------+----------------+-----+
|           NULL|            NULL|  366|
|           High|             Dry|  659|
|           High|           Humid|  470|
|           High|         Optimal| 1660|
|            Low|             Dry| 1060|
|            Low|           Humid|  312|
|            Low|         Optimal| 1447|
|            Mid|             Dry| 1019|
|            Mid|           Humid|  536|
|            Mid|         Optimal| 1828|
+---------------+----------------+-----+

The count for each combination of levels are outputted! 

We can also use this function to count how many missing values we have for a variable. Recall that we created `AH_is_missing` variable. We can convert this column to a string and use this method.

In [36]:
air.df = air.df.withColumn(
    "AH_is_missing_str",
    F.col("AH_is_missing").cast("string")
)

air.count_level("AH_is_missing_str").show()

+-----------------+-----+
|AH_is_missing_str|count|
+-----------------+-----+
|            false| 8991|
|             true|  366|
+-----------------+-----+

We have 366 missing values!

If we just pass `AH_is_missing`, our program won't accept it! Because we set up our code to only accept string variables, and this is a Boolean column.

In [37]:
air.count_level("AH_is_missing")

Column 'AH_is_missing' is a numeric column. Please provide a string column!

# From Pandas

Now let's try reading the data in from `pandas`!

In [38]:
air2 = SparkDataCheck.from_pd(
    spark,
    pd.read_csv("air.csv")
)

air2.df.show()

+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|Unnamed: 0|     Date|    Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|         0|3/10/2004|18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|         1|3/10/2004|19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|         2|3/10/2004|20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|         3|3/10/2004|21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|         4|3/10/2004|22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
|         5|3/10/2004|23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|
|         6|3/11/2004| 0:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|
|         7|3/11/2004| 1:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|
|         8|3/11/2004| 2:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|
|         9|3/11/2004| 3:00:00|   0.6|       1010|      19|     1.7|          561|   -200|        1705|   -200|        1235|        501|10.3|60.2|0.7517|
|        10|3/11/2004| 4:00:00|-200.0|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|
|        11|3/11/2004| 5:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|
|        12|3/11/2004| 6:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|
|        13|3/11/2004| 7:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|
|        14|3/11/2004| 8:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|
|        15|3/11/2004| 9:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|
|        16|3/11/2004|10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|
|        17|3/11/2004|11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|
|        18|3/11/2004|12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|
|        19|3/11/2004|13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|
+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 20 rows

Let's see what the min and max is if we don't recode the missing values for `CO(GT)`.

In [39]:
air2.min_max("CO(GT)").show()

+----------+----------+
|CO(GT)_min|CO(GT)_max|
+----------+----------+
|    -200.0|      11.9|
+----------+----------+

# Part 2 

Let's read in the NFL data to do some basic analysis using spark. We'll need to import `Pandas on Spark`.

In [41]:
import pyspark.pandas as ps
ps.set_option("compute.fail_on_ansi_mode", False)


nfl = pd.read_csv("weekly_nfl_data.csv")
nfl_df = ps.from_pandas(nfl)

/home/jupyter-bchen29@ncsu.edu/.local/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: The config 'spark.sql.ansi.enabled' is set to True. This can cause unexpected behavior from pandas API on Spark since pandas API on Spark follows the behavior of pandas, not SQL.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

See the first 5 rows of this data set.

In [42]:
nfl_df.head()

    player_id player_name    player_display_name position position_group headshot_url recent_team  season  week season_type opponent_team  completions  attempts  passing_yards  passing_tds  interceptions  sacks  sack_yards  sack_fumbles  sack_fumbles_lost  passing_air_yards  passing_yards_after_catch  passing_first_downs  passing_epa  passing_2pt_conversions  pacr  dakota  carries  rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  rushing_first_downs  rushing_epa  rushing_2pt_conversions  receptions  targets  receiving_yards  receiving_tds  receiving_fumbles  receiving_fumbles_lost  receiving_air_yards  receiving_yards_after_catch  receiving_first_downs  receiving_epa  receiving_2pt_conversions  racr  target_share  air_yards_share  wopr  special_teams_tds  fantasy_points  fantasy_points_ppr
0  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     1         REG           DEN            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       16           60.0            1              0.0                   0.0                  4.0     6.248771                        0           1        1              7.0              0                0.0                     0.0                  0.0                          0.0                    0.0       0.292378                          0   0.0      0.052632              NaN   NaN                0.0            12.7                13.7
1  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     2         REG           ARI            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        9           33.0            0              0.0                   0.0                  1.0    -1.434950                        0           3        4             18.0              0                0.0                     0.0                  0.0                          0.0                    1.0       0.377009                          0   0.0      0.117647              NaN   NaN                0.0             5.1                 8.1
2  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     4         REG           BUF            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        3            2.0            0              0.0                   0.0                  0.0    -1.539952                        0           0        1              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.699578                          0   NaN      0.023810              NaN   NaN                0.0             0.2                 0.2
3  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     7         REG            LA            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        6           27.0            0              0.0                   0.0                  0.0     0.216051                        0           2        2              8.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.228454                          0   0.0      0.050000              NaN   NaN                0.0             3.5                 5.5
4  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     8         REG            NO            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       13           39.0            0              0.0                   0.0                  2.0    -2.972259                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0             3.9                 3.9

Check the column names

In [43]:
nfl_df.columns

Index(['player_id', 'player_name', 'player_display_name', 'position',
       'position_group', 'headshot_url', 'recent_team', 'season', 'week',
       'season_type', 'opponent_team', 'completions', 'attempts',
       'passing_yards', 'passing_tds', 'interceptions', 'sacks', 'sack_yards',
       'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards',
       'passing_yards_after_catch', 'passing_first_downs', 'passing_epa',
       'passing_2pt_conversions', 'pacr', 'dakota', 'carries', 'rushing_yards',
       'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost',
       'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions',
       'receptions', 'targets', 'receiving_yards', 'receiving_tds',
       'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards',
       'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa',
       'receiving_2pt_conversions', 'racr', 'target_share', 'air_yards_share',
       'wopr', 'special_teams_tds', 'fantasy_points', 'fantasy_points_ppr'],
      dtype='object')

We are only interested in looking at QB stats for the seasons 2005 to 2023. So, let's subset the data accordingly and only include columns `player_display_name`, `season`, `week`, `completions`, `attempts`, `passing_yards`, `passing_tds`, and `interceptions`.

In [46]:
qb = nfl_df[(nfl_df["position"] == "QB") &
              (nfl_df["season_type"] == "REG") &
              (nfl_df["season"] >= 2005) &
              (nfl_df["season"] <= 2023)
             ][["player_display_name", "season", "week",
                "completions", "attempts", "passing_yards",
                "passing_tds", "interceptions"
               ]]

/home/jupyter-bchen29@ncsu.edu/.local/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: The config 'spark.sql.ansi.enabled' is set to True. This can cause unexpected behavior from pandas API on Spark since pandas API on Spark follows the behavior of pandas, not SQL.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

We want to know for each player and season combination, the sum and mean of each of the statistical quantities.

In [50]:
qb_summary = (
    qb.groupby(["player_display_name", "season"])[
        ["completions", "attempts", "passing_yards", "passing_tds", "interceptions"]
    ]
    .agg(["sum", "mean"])
)
qb_summary.head()

/home/jupyter-bchen29@ncsu.edu/.local/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: The config 'spark.sql.ansi.enabled' is set to True. This can cause unexpected behavior from pandas API on Spark since pandas API on Spark follows the behavior of pandas, not SQL.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

                           completions            attempts            passing_yards             passing_tds           interceptions
                                   sum       mean      sum       mean           sum        mean         sum      mean           sum      mean
player_display_name season
Jeff Blake          2005             8   4.000000        9   4.500000          55.0   27.500000           1  0.500000           0.0  0.000000
Daunte Culpepper    2005           139  19.857143      216  30.857143        1564.0  223.428571           6  0.857143          12.0  1.714286
Kerry Collins       2005           302  20.133333      566  37.733333        3759.0  250.600000          20  1.333333          13.0  0.866667
Tony Banks          2005            14  14.000000       25  25.000000         173.0  173.000000           1  1.000000           2.0  2.000000
Charlie Batch       2005            23   7.666667       36  12.000000         246.0   82.000000           1  0.333333           1.0  0.333333

Using this information, we want to create 2 more summaries: Completion percentage and TD-Interception ratio. We want to compute the ratio only where the denominator (total interception) is not 0.

In [68]:
qb_summary["completion_percentage"] = (
    qb_summary[("completions", "sum")] / qb_summary[("attempts", "sum")]
)

qb_summary["td_int_ratio"] = (
    qb_summary[("passing_tds", "sum")] / qb_summary[("interceptions", "sum")]
    .where(qb_summary[("interceptions", "sum")] != 0)
)

/home/jupyter-bchen29@ncsu.edu/.local/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: The config 'spark.sql.ansi.enabled' is set to True. This can cause unexpected behavior from pandas API on Spark since pandas API on Spark follows the behavior of pandas, not SQL.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

In [69]:
qb_summary.head()

                           completions            attempts            passing_yards             passing_tds           interceptions           completion_percentage td_int_ratio
                                   sum       mean      sum       mean           sum        mean         sum      mean           sum      mean
player_display_name season
Jeff Blake          2005             8   4.000000        9   4.500000          55.0   27.500000           1  0.500000           0.0  0.000000              0.888889          NaN
Daunte Culpepper    2005           139  19.857143      216  30.857143        1564.0  223.428571           6  0.857143          12.0  1.714286              0.643519     0.500000
Kerry Collins       2005           302  20.133333      566  37.733333        3759.0  250.600000          20  1.333333          13.0  0.866667              0.533569     1.538462
Tony Banks          2005            14  14.000000       25  25.000000         173.0  173.000000           1  1.000000           2.0  2.000000              0.560000     0.500000
Charlie Batch       2005            23   7.666667       36  12.000000         246.0   82.000000           1  0.333333           1.0  0.333333              0.638889     1.000000

I wonder why Blake have 0 interceptions for 2005!

Now, let's see who have at least 50 attempts.

In [70]:
attempt_50 = qb_summary[qb_summary[("attempts", "sum")] >= 50]
attempt_50.head()

/home/jupyter-bchen29@ncsu.edu/.local/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: The config 'spark.sql.ansi.enabled' is set to True. This can cause unexpected behavior from pandas API on Spark since pandas API on Spark follows the behavior of pandas, not SQL.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

                           completions            attempts            passing_yards             passing_tds           interceptions           completion_percentage td_int_ratio
                                   sum       mean      sum       mean           sum        mean         sum      mean           sum      mean
player_display_name season
Daunte Culpepper    2005           139  19.857143      216  30.857143        1564.0  223.428571           6  0.857143          12.0  1.714286              0.643519     0.500000
Kerry Collins       2005           302  20.133333      566  37.733333        3759.0  250.600000          20  1.333333          13.0  0.866667              0.533569     1.538462
Jeff Garcia         2005           102  17.000000      173  28.833333         937.0  156.166667           3  0.500000           6.0  1.000000              0.589595     0.500000
Brett Favre         2005           372  23.250000      607  37.937500        3881.0  242.562500          20  1.250000          29.0  1.812500              0.612850     0.689655
Todd Bouman         2005            68  13.600000      122  24.400000         722.0  144.400000           2  0.400000           7.0  1.400000              0.557377     0.285714

Let's sort the rows descending by completion percentage and report the first 40 players. Notice that there are `NaN` values because of a 0 in the denominator. We are not interesting in those, so exclude them!

In [80]:
top40_completion = attempt_50[
    attempt_50["completion_percentage"].notna()
].sort_values(
    by="completion_percentage",
    ascending=False
).head(40)

top40_completion

                           completions            attempts            passing_yards             passing_tds           interceptions           completion_percentage td_int_ratio
                                   sum       mean      sum       mean           sum        mean         sum      mean           sum      mean
player_display_name season
C.J. Beathard       2023            40   6.666667       53   8.833333         349.0   58.166667           1  0.166667           0.0  0.000000              0.754717          NaN
Colt McCoy          2021            74  10.571429       99  14.142857         740.0  105.714286           3  0.428571           1.0  0.142857              0.747475     3.000000
Matt Schaub         2019            50  10.000000       67  13.400000         580.0  116.000000           3  0.600000           1.0  0.200000              0.746269     3.000000
Drew Brees          2018           364  24.266667      489  32.600000        3992.0  266.133333          32  2.133333           5.0  0.333333              0.744376     6.400000
                    2019           281  25.545455      378  34.363636        2979.0  270.818182          27  2.454545           4.0  0.363636              0.743386     6.750000
Mason Rudolph       2023            55  13.750000       74  18.500000         719.0  179.750000           3  0.750000           0.0  0.000000              0.743243          NaN
Taysom Hill         2020            88   5.500000      121   7.562500         928.0   58.000000           4  0.250000           2.0  0.125000              0.727273     2.000000
Nick Foles          2018           141  28.200000      195  39.000000        1413.0  282.600000           7  1.400000           4.0  0.800000              0.723077     1.750000
Drew Brees          2017           386  24.125000      536  33.500000        4334.0  270.875000          23  1.437500           8.0  0.500000              0.720149     2.875000
Sam Bradford        2016           395  26.333333      552  36.800000        3877.0  258.466667          20  1.333333           5.0  0.333333              0.715580     4.000000
Drew Brees          2011           471  29.437500      660  41.250000        5535.0  345.937500          46  2.875000          14.0  0.875000              0.713636     3.285714
Colt McCoy          2014            91  18.200000      128  25.600000        1057.0  211.400000           4  0.800000           3.0  0.600000              0.710938     1.333333
Aaron Rodgers       2020           372  23.250000      526  32.875000        4299.0  268.687500          48  3.000000           5.0  0.312500              0.707224     9.600000
Bailey Zappe        2022            65  16.250000       92  23.000000         781.0  195.250000           5  1.250000           3.0  0.750000              0.706522     1.666667
Drew Brees          2009           363  24.200000      514  34.266667        4388.0  292.533333          34  2.266667          11.0  0.733333              0.706226     3.090909
                    2020           275  22.916667      390  32.500000        2942.0  245.166667          24  2.000000           6.0  0.500000              0.705128     4.000000
Joe Burrow          2021           366  22.875000      520  32.500000        4611.0  288.187500          34  2.125000          14.0  0.875000              0.703846     2.428571
Derek Carr          2019           361  22.562500      513  32.062500        4054.0  253.375000          21  1.312500           8.0  0.500000              0.703704     2.625000
Jake Browning       2023           171  19.000000      243  27.000000        1936.0  215.111111          12  1.333333           7.0  0.777778              0.703704     1.714286
Chase Daniel        2019            45  15.000000       64  21.333333         435.0  145.000000           3  1.000000           2.0  0.666667              0.703125     1.500000
Ryan Tannehill      2019           201  16.750000      286  23.833333        2742.0  228.500000          22  1.833333           6.0  0.500000              0.702797     3.666667
Deshaun Watson      2020           382  23.875000      544  34.000000        4823.0  301.437500          33  2.062500           7.0  0.437500              0.702206     4.714286
Alex Smith          2012           153  15.300000      218  21.800000        1737.0  173.700000          13  1.300000           5.0  0.500000              0.701835     2.600000
Kirk Cousins        2018           425  26.562500      606  37.875000        4298.0  268.625000          30  1.875000          10.0  0.625000              0.701320     3.000000
Jamie Martin        2005           124  15.500000      177  22.125000        1277.0  159.625000           5  0.625000           7.0  0.875000              0.700565     0.714286
Drew Brees          2016           471  29.437500      673  42.062500        5208.0  325.500000          37  2.312500          15.0  0.937500              0.699851     2.466667
Tony Romo           2014           304  20.266667      435  29.000000        3705.0  247.000000          34  2.266667           9.0  0.600000              0.698851     3.777778
Matt Ryan           2016           373  23.312500      534  33.375000        4944.0  309.000000          38  2.375000           7.0  0.437500              0.698502     5.428571
Kirk Cousins        2015           379  23.687500      543  33.937500        4166.0  260.375000          29  1.812500          11.0  0.687500              0.697974     2.636364
Geno Smith          2022           399  23.470588      572  33.647059        4282.0  251.882353          30  1.764706          11.0  0.647059              0.697552     2.727273
Chase Daniel        2018            53  13.250000       76  19.000000         515.0  128.750000           3  0.750000           2.0  0.500000              0.697368     1.500000
Carson Wentz        2018           279  25.363636      401  36.454545        3074.0  279.454545          21  1.909091           7.0  0.636364              0.695761     3.000000
Dak Prescott        2023           410  24.117647      590  34.705882        4516.0  265.647059          36  2.117647           9.0  0.529412              0.694915     4.000000
Philip Rivers       2013           378  23.625000      544  34.000000        4478.0  279.875000          32  2.000000          11.0  0.687500              0.694853     2.909091
Tony Romo           2010           148  24.666667      213  35.500000        1605.0  267.500000          11  1.833333           7.0  1.166667              0.694836     1.571429
Kirk Cousins        2023           216  27.000000      311  38.875000        2331.0  291.375000          18  2.250000           5.0  0.625000              0.694534     3.600000
Matt Ryan           2018           422  26.375000      608  38.000000        4924.0  307.750000          35  2.187500           7.0  0.437500              0.694079     5.000000
Brock Purdy         2023           308  19.250000      444  27.750000        4280.0  267.500000          31  1.937500          11.0  0.687500              0.693694     2.818182
Jim Sorgi           2005            43   8.600000       62  12.400000         444.0   88.800000           3  0.600000           1.0  0.200000              0.693548     3.000000
Brandon Weeden      2015            97  16.166667      140  23.333333        1043.0  173.833333           5  0.833333           2.0  0.333333              0.692857     2.500000

Do the same for TD-Intercept ratio, and see top 40 players.

In [81]:
top40_td_int = attempt_50[
    attempt_50["td_int_ratio"].notna()
].sort_values(
    by="td_int_ratio",
    ascending=False
).head(40)

top40_td_int

                           completions            attempts            passing_yards             passing_tds           interceptions           completion_percentage td_int_ratio
                                   sum       mean      sum       mean           sum        mean         sum      mean           sum      mean
player_display_name season
Tom Brady           2016           291  24.250000      432  36.000000        3554.0  296.166667          28  2.333333           2.0  0.166667              0.673611    14.000000
Nick Foles          2013           203  15.615385      317  24.384615        2891.0  222.384615          27  2.076923           2.0  0.153846              0.640379    13.500000
Josh McCown         2013           149  18.625000      224  28.000000        1829.0  228.625000          13  1.625000           1.0  0.125000              0.665179    13.000000
Aaron Rodgers       2018           372  23.250000      597  37.312500        4442.0  277.625000          25  1.562500           2.0  0.125000              0.623116    12.500000
Damon Huard         2006           148  14.800000      244  24.400000        1878.0  187.800000          11  1.100000           1.0  0.100000              0.606557    11.000000
Aaron Rodgers       2020           372  23.250000      526  32.875000        4299.0  268.687500          48  3.000000           5.0  0.312500              0.707224     9.600000
                    2021           366  22.875000      531  33.187500        4115.0  257.187500          37  2.312500           4.0  0.250000              0.689266     9.250000
Tom Brady           2010           324  20.250000      492  30.750000        3900.0  243.750000          36  2.250000           4.0  0.250000              0.658537     9.000000
Jake Delhomme       2007            55  18.333333       86  28.666667         617.0  205.666667           8  2.666667           1.0  0.333333              0.639535     8.000000
Aaron Rodgers       2014           341  21.312500      520  32.500000        4381.0  273.812500          38  2.375000           5.0  0.312500              0.655769     7.600000
                    2011           342  22.800000      501  33.400000        4636.0  309.066667          45  3.000000           6.0  0.400000              0.682635     7.500000
Drew Brees          2019           281  25.545455      378  34.363636        2979.0  270.818182          27  2.454545           4.0  0.363636              0.743386     6.750000
Aaron Rodgers       2019           353  22.062500      569  35.562500        4002.0  250.125000          26  1.625000           4.0  0.250000              0.620387     6.500000
Drew Brees          2018           364  24.266667      489  32.600000        3992.0  266.133333          32  2.133333           5.0  0.333333              0.744376     6.400000
Patrick Mahomes     2020           390  26.000000      588  39.200000        4740.0  316.000000          38  2.533333           6.0  0.400000              0.663265     6.333333
Tom Brady           2007           398  24.875000      578  36.125000        4806.0  300.375000          50  3.125000           8.0  0.500000              0.688581     6.250000
Russell Wilson      2019           341  21.312500      516  32.250000        4110.0  256.875000          31  1.937500           5.0  0.312500              0.660853     6.200000
David Garrard       2007           208  17.333333      325  27.083333        2509.0  209.083333          18  1.500000           3.0  0.250000              0.640000     6.000000
Matthew Stafford    2010            57  14.250000       96  24.000000         535.0  133.750000           6  1.500000           1.0  0.250000              0.593750     6.000000
Lamar Jackson       2019           265  17.666667      401  26.733333        3127.0  208.466667          36  2.400000           6.0  0.400000              0.660848     6.000000
Dak Prescott        2016           311  19.437500      459  28.687500        3667.0  229.187500          23  1.437500           4.0  0.250000              0.677560     5.750000
Aaron Rodgers       2016           401  25.062500      610  38.125000        4428.0  276.750000          40  2.500000           7.0  0.437500              0.657377     5.714286
Peyton Manning      2013           450  28.125000      659  41.187500        5477.0  342.312500          55  3.437500          10.0  0.625000              0.682853     5.500000
Matt Ryan           2016           373  23.312500      534  33.375000        4944.0  309.000000          38  2.375000           7.0  0.437500              0.698502     5.428571
Alex Smith          2017           341  22.733333      505  33.666667        4042.0  269.466667          26  1.733333           5.0  0.333333              0.675248     5.200000
Patrick Mahomes     2019           319  22.785714      484  34.571429        4031.0  287.928571          26  1.857143           5.0  0.357143              0.659091     5.200000
Tom Brady           2015           402  25.125000      624  39.000000        4770.0  298.125000          36  2.250000           7.0  0.437500              0.644231     5.142857
Jeff Garcia         2006           116  14.500000      188  23.500000        1309.0  163.625000          10  1.250000           2.0  0.250000              0.617021     5.000000
Matt Ryan           2018           422  26.375000      608  38.000000        4924.0  307.750000          35  2.187500           7.0  0.437500              0.694079     5.000000
Russell Wilson      2018           280  17.500000      427  26.687500        3448.0  215.500000          35  2.187500           7.0  0.437500              0.655738     5.000000
Geno Smith          2021            65  16.250000       95  23.750000         702.0  175.500000           5  1.250000           1.0  0.250000              0.684211     5.000000
Aaron Rodgers       2012           371  23.187500      552  34.500000        4295.0  268.437500          39  2.437500           8.0  0.500000              0.672101     4.875000
Ryan Tannehill      2020           315  19.687500      481  30.062500        3819.0  238.687500          34  2.125000           7.0  0.437500              0.654886     4.857143
Brett Favre         2009           364  22.750000      532  33.250000        4202.0  262.625000          33  2.062500           7.0  0.437500              0.684211     4.714286
Carson Wentz        2017           265  20.384615      440  33.846154        3296.0  253.538462          33  2.538462           7.0  0.538462              0.602273     4.714286
Deshaun Watson      2020           382  23.875000      544  34.000000        4823.0  301.437500          33  2.062500           7.0  0.437500              0.702206     4.714286
Kirk Cousins        2021           372  23.250000      561  35.062500        4221.0  263.812500          33  2.062500           7.0  0.437500              0.663102     4.714286
Derek Carr          2016           357  23.800000      560  37.333333        3937.0  262.466667          28  1.866667           6.0  0.400000              0.637500     4.666667
Jameis Winston      2021            95  13.571429      161  23.000000        1170.0  167.142857          14  2.000000           3.0  0.428571              0.590062     4.666667
C.J. Stroud         2023           319  21.266667      499  33.266667        4108.0  273.866667          23  1.533333           5.0  0.333333              0.639279     4.600000